=== BibalexIRILS/WAMCP/WAMCP/WebContent/Schema/xsa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bibalex.org/xsa"
	xmlns:xsa="http://www.bibalex.org/xsa" elementFormDefault="qualified">
	<import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
	<!--
		doesn't work behind proxy: "http://www.w3.org/2001/03/xml.xsd"/>
	-->

	<!-- Simple Types -->
	<simpleType name="TStandardNsUris">
		<restriction base="anyURI">
			<enumeration value="http://www.w3.org/XML/1998/namespace"/>
		</restriction>
	</simpleType>

	<simpleType name="TNsUri">
		<union memberTypes="xsa:TStandardNsUris anyURI"/>
	</simpleType>

	<simpleType name="TUiDivisionsenum">
		<restriction base="token">
			<enumeration value="field"/>
			<enumeration value="container"/>
			<enumeration value="section"/>
			<enumeration value="area"/>
			<enumeration value="site"/>
		</restriction>
	</simpleType>

	<simpleType name="TUsersList">
		<list itemType="xsa:TValidUserName"/>
	</simpleType>

	<simpleType name="TValidUserName">
		<restriction base="string"/>
	</simpleType>

	<simpleType name="TLocatorString">
		<restriction base="string"/>
	</simpleType>

	<simpleType name="TValuesList">
		<list itemType="anySimpleType"/>
	</simpleType>

	<!-- Complex Types -->

	<complexType name="instanceType">
		<sequence minOccurs="0" maxOccurs="unbounded">
			<element ref="xsa:ui" minOccurs="1" maxOccurs="1"/>

			<element ref="xsa:readAccess" minOccurs="0" maxOccurs="unbounded"/>
			<!--
				TODOL minOccurs 1
			-->

			<element ref="xsa:writeAccess" minOccurs="0" maxOccurs="unbounded"/>
			<!--
				TODOL minOccurs 1
			-->

			<element ref="xsa:responsible" minOccurs="0" maxOccurs="1"/>
			<!--
				TODOL minOccurs 1
			-->

			<element ref="xsa:messages" minOccurs="0" maxOccurs="1"/>

			<element ref="xsa:attribute" minOccurs="0" maxOccurs="unbounded"/>

			<choice minOccurs="0" maxOccurs="1">

				<element ref="xsa:defaultVal" minOccurs="0" maxOccurs="1"/>

				<!--				<element ref="xsa:mixed" minOccurs="0" maxOccurs="1" />-->
			</choice>

			<element ref="xsa:indexed"/>

			<element ref="xsa:baseShift"/>
		</sequence>

		<attribute ref="xml:id"/>
		<attribute name="under" type="IDREF"/>
		<attribute name="repeat" type="xsa:TYesNo" default="no" use="optional"/>
		<attribute name="mixed" type="xsa:TYesNo" default="no" use="optional"/>
		<attribute name="mixedContLabel" type="string" default="Text" use="optional"/>
		<attribute name="authorityList" type="IDREF" use="optional"/>
		<attribute name="group" type="IDREF" use="optional"/>
		<attribute name="facs" type="xsa:TYesNo" use="optional" default="no"/>
	</complexType>

	<simpleType name="TYesNo">
		<restriction base="token">
			<enumeration value="yes"/>
			<enumeration value="no"/>
			<enumeration value="optional"/>
		</restriction>
	</simpleType>

	<complexType name="dataHolderType">



		<sequence minOccurs="0" maxOccurs="unbounded">

			<element ref="xsa:dataType" minOccurs="0" maxOccurs="1"/>
			<element ref="xsa:instance" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="locator" type="xsa:TLocatorString"/>


	</complexType>

	<complexType name="messagesType">
		<sequence minOccurs="0" maxOccurs="1">
			<element ref="xsa:label" minOccurs="0" maxOccurs="1"/>
			<element ref="xsa:help" minOccurs="0" maxOccurs="1"/>
			<!--			<element ref="xsa:invalid" minOccurs="0" maxOccurs="1" />-->
			<!--			<element ref="xsa:missing" minOccurs="0" maxOccurs="1" />-->
		</sequence>
		<attribute name="locale" type="token" default="en"/>
	</complexType>



	<complexType name="annotatorType">
		<complexContent>
			<extension base="xsa:instanceType">
				<attribute name="eltName" use="required" type="token"/>
				<attribute name="text" use="required" type="xsa:TYesNo"/>
			</extension>
		</complexContent>
	</complexType>

	<!--
		<complexType name="elementTypeAbstract" abstract="true"> <choice
		minOccurs="1" maxOccurs="1"> <element ref="xsa:dataHolderProps" />
		<element ref="xsa:annotatorProps" /> </choice> </complexType>
	-->

	<!-- Elements -->
	<element name="groupDef">
		<complexType>
			<choice minOccurs="1" maxOccurs="unbounded">
				<element ref="xsa:messages"/>
			</choice>
			<attribute ref="xml:id" use="required"/>
			<attribute name="ixInUi" use="optional" type="decimal"/>
			<attribute name="decorate" use="optional" type="xsa:TYesNo" default="no"/>

		</complexType>
	</element>


	<element name="readAccess" type="xsa:TUsersList"/>

	<element name="writeAccess" type="xsa:TUsersList"/>

	<element name="responsible">
		<complexType>
			<simpleContent>

				<extension base="xsa:TValidUserName">
					<attribute name="required" type="boolean" use="required"/>
				</extension>

			</simpleContent>
		</complexType>
	</element>

	<element name="label" type="string"/>
	<element name="help" type="string"/>
	<!--	<element name="invalid" type="string" />-->
	<!--	<element name="missing" type="string" />-->

	<element name="messages" type="xsa:messagesType"/>

	<element name="attribute">
		<complexType>
			<attribute name="name" type="Name" use="required"/>
			<attribute name="nsuri" type="xsa:TNsUri" use="required"/>
			<attribute name="value" type="string" use="required"/>
		</complexType>
	</element>

	<element name="defaultVal" type="string"/>

	<!--	<element name="mixed">-->
	<!--		<complexType mixed="true">-->
	<!---->
	<!--			<simpleContent>-->
	<!--				<extension base="string"></extension>-->
	<!--			</simpleContent>-->
	<!---->
	<!--		</complexType>-->
	<!--	</element>-->

	<element name="ui" type="xsa:TUiDivisionsenum"/>

	<element name="authListDef">
		<complexType>
			<simpleContent>
				<extension base="string">
					<!-- "xsa:TValuesList"> -->
					<attribute ref="xml:id" use="required"/>
					<attribute name="grows" type="boolean" default="true" use="optional"/>
				</extension>
			</simpleContent>
		</complexType>
	</element>

	<element name="instance" type="xsa:instanceType"/>

	<element name="dataType">
		<complexType>
			<simpleContent>
				<extension base="string">
					<attribute name="list" type="boolean" default="true"/>
				</extension>
			</simpleContent>
		</complexType>
	</element>

	<element name="dataHolder" type="xsa:dataHolderType"/>

	<element name="annotator" type="xsa:annotatorType"/>

	<element name="indexed">
		<complexType>
			<simpleContent>
				<extension base="token">
					<attribute name="summary" type="xsa:TYesNo"/>
					<attribute name="key" type="xsa:TYesNo"/>
					<attribute name="solrType" use="optional">
						<simpleType>
							<restriction base="string">
								<whiteSpace value="preserve"/>
							</restriction>
						</simpleType>
					</attribute>
					<attribute name="advancedSearch" type="string"/>
				</extension>
			</simpleContent>
		</complexType>
	</element>

	<element name="baseShift">
		<complexType>
			<simpleContent>
				<extension base="anySimpleType">
					<attribute name="pattern" use="required" type="string"/>
				</extension>
			</simpleContent>
		</complexType>
	</element>
	<!--	minOccurs="0" maxOccurs="1" -->

	<!--	<element name="ref" type="xsa:TLocatorString" />-->

	<!--
		<element name="element"> <complexType> <complexContent> <extension
		base="xsa:elementTypeAbstract"> <attribute name="locator"
		type="xsa:TLocatorString" use="required"></attribute> </extension>
		</complexContent> </complexType> </element> <attribute name="locator"
		type="xsa:TLocatorString" use="required"></attribute>
	-->

	<!-- Document -->

	<element name="xsa">
		<complexType>
			<sequence minOccurs="0" maxOccurs="unbounded">
				<element ref="xsa:authListDef" minOccurs="0" maxOccurs="unbounded"/>
				<element ref="xsa:annotator" minOccurs="0" maxOccurs="unbounded"/>
				<element ref="xsa:dataHolder" minOccurs="0" maxOccurs="unbounded"/>
				<element ref="xsa:groupDef" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
</schema>

=== BibalexIRILS/WAMCP/XSAAuthoringTool/src/main/webapp/Schema/xsa.xsd.xsa.xml
<!--
   Copyright 2013 Bibliotheca Alexandrina, Wellcome Trust Library

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->

<?xml version="1.0" encoding="UTF-8"?>
<xsa:xsa xmlns:xsa="http://www.bibalex.org/xsa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-xsa:instance" xsi:schemaLocation="http://www.bibalex.org/xsa xsa.xsd http://www.w3.org/XML/1998/namespace xml.xsd">
  <xsa:authListDef xml:id="alYesNo"> yes | no</xsa:authListDef>
  
  <xsa:dataHolder locator="/xsa">
    <xsa:instance mixed="no" repeat="no" xml:id="site">
      <xsa:ui>site</xsa:ui>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder>
    <xsa:instance mixed="no" repeat="no" xml:id="areaDHs" under="site">
      <xsa:ui>area</xsa:ui>
      <xsa:messages>
        <xsa:label>Data Holders</xsa:label>
        <xsa:help>Elements that hold data, and their hierarchy in XML and visually</xsa:help>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder>
    <xsa:instance mixed="no" repeat="no" xml:id="areaAutLists" under="site">
      <xsa:ui>area</xsa:ui>
<!--      <xsa:baseShift pattern="/xsa/authListDef[?Authority List Ix]"/>-->
      <xsa:messages>
        <xsa:label>Authority Lists</xsa:label>
        <xsa:help>Lists of values to be allowed in certain fields</xsa:help>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  
  <xsa:dataHolder>
    <xsa:instance mixed="no" repeat="no" xml:id="areaAnnotsGrps" under="site">
      <xsa:ui>area</xsa:ui>
      <xsa:messages>
        <xsa:label>Annotators and Groups</xsa:label>
        <xsa:help>Elements that are used to Annotate data in mixed content elements. Also Groupings of fields, for visually compressing long pages. Combined together in one Area to show using sections</xsa:help>
      </xsa:messages>
    </xsa:instance>

<!--  <xsa:dataHolder>-->
<!--    <xsa:instance mixed="no" repeat="no" xml:id="areaGroups" under="site">-->
<!--      <xsa:ui>area</xsa:ui>-->
<!--      <xsa:messages>-->
<!--        <xsa:label>Groups</xsa:label>-->
<!--        <xsa:help>Groupings of fields, for visually compressing long pages</xsa:help>-->
<!--      </xsa:messages>-->
<!--    </xsa:instance>-->
<!--  </xsa:dataHolder>-->

	<xsa:instance mixed="no" repeat="no" xml:id="secAnnots" under="areaAnnotsGrps">
      <xsa:ui>section</xsa:ui>
      <xsa:messages>
        <xsa:label>Annotators</xsa:label>
      </xsa:messages>
    </xsa:instance>
    
   	<xsa:instance mixed="no" repeat="no" xml:id="secGroups" under="areaAnnotsGrps">
      <xsa:ui>section</xsa:ui>
      <xsa:messages>
        <xsa:label>Groups</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
 
  
  <xsa:dataHolder locator="/xsa/dataHolder">
    <xsa:instance mixed="no" under="areaDHs" xml:id="cntDH">
      <xsa:ui>container</xsa:ui>
      <xsa:messages>
        <xsa:label>Data Holder</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/@locator">
    <xsa:instance mixed="no" repeat="no" under="cntDH">
      <xsa:responsible required="true" />
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Locator String</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/dataType">
    <xsa:instance mixed="no" repeat="no" under="cntDH">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Data Type</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance">
    <xsa:instance mixed="no" under="cntDH" xml:id="cntInst">
      <xsa:ui>container</xsa:ui>
      <xsa:messages>
        <xsa:label>Instance</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/attribute">
    <xsa:instance mixed="no" under="cntInst" xml:id="cntAttr">
      <xsa:ui>container</xsa:ui>
      <xsa:messages>
        <xsa:label>Attribute</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/attribute/@name">
    <xsa:instance mixed="no" repeat="no" under="cntAttr">
      <xsa:responsible required="true" />
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Name</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/attribute/@value">
    <xsa:instance mixed="no" repeat="no" under="cntAttr">
      <xsa:responsible required="true" />
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Value</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/attribute/@nsuri">
    <xsa:instance mixed="no" repeat="no" under="cntAttr">
      <xsa:responsible required="true" />
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Name Space URI</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/@xml:id">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Id in XSA.XML</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/messages/label">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Label in UI</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/@under">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:responsible required="true" />
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Parent Instance</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/ui">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:responsible required="true" />
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>UI</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/responsible/@required">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Required</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/@repeat">
    <xsa:instance mixed="no" repeat="no" under="cntInst" authorityList="alYesNo">
      <xsa:ui>field</xsa:ui>
      <xsa:defaultVal>no</xsa:defaultVal>
      <xsa:messages>
        <xsa:label>Repeat</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/@mixed">
    <xsa:instance mixed="no" repeat="no" under="cntInst" authorityList="alYesNo">
      <xsa:ui>field</xsa:ui>
      <xsa:defaultVal>no</xsa:defaultVal>
      <xsa:messages>
        <xsa:label>Mixed</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/defaultVal">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Default Value</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
<!--  <xsa:dataHolder locator="/xsa/dataHolder/instance/mixed">-->
<!--    <xsa:instance mixed="no" repeat="no" under="cntInst">-->
<!--      <xsa:ui>field</xsa:ui>-->
<!--      <xsa:messages>-->
<!--        <xsa:label>Default Value (Mixed)</xsa:label>-->
<!--      </xsa:messages>-->
<!--    </xsa:instance>-->
<!--  </xsa:dataHolder>-->
  <xsa:dataHolder locator="/xsa/dataHolder/instance/@authorityList">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Authority List</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/readAccess">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Read Access</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/writeAccess">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Write access</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/@facs">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Facsimilie</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/@group">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Group</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
  <xsa:dataHolder locator="/xsa/dataHolder/instance/messages/help">
    <xsa:instance mixed="no" repeat="no" under="cntInst">
      <xsa:ui>field</xsa:ui>
      <xsa:messages>
        <xsa:label>Help Text</xsa:label>
      </xsa:messages>
    </xsa:instance>
  </xsa:dataHolder>
